name: CI for ordering.API

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Step to checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step to set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # Specify the version of .NET to install

    # Step to set up Docker Buildx, a builder for multi-platform builds
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step to cache Docker layers to speed up subsequent builds
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache  # Path to cache Docker layers
        key: ${{ runner.os }}-buildx-${{ github.sha }}  # Cache key
        restore-keys: |
          ${{ runner.os }}-buildx-  # Restore key to use if the specific key is not found

    # Step to log in to DockerHub using the provided credentials
    - name: Login to DockerHub
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  # Use DockerHub username from secrets
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}  # Use DockerHub password from secrets
      run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin  # Log in to DockerHub

    # Step to build and push the Docker image
    - name: Build and Push Docker image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  # Use DockerHub username from secrets
        IMAGE_NAME: ordering-api  # Define the image name
      run: |
        # Build the Docker image using the specified Dockerfile and build arguments
        IMAGE_TAG=$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA}
        docker build --file Services/Ordering/Ordering.API/Dockerfile --build-arg BUILD_CONFIGURATION=Release -t ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG} -t ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest .
        # Push both tags to DockerHub
        docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}
        docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest
